# Generated by Django 5.1.2 on 2024-10-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_comment_created_at_alter_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='auto_reply_delay',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
